CREATE SEQUENCE AMOUNT_SEQUENCE START WITH 1 INCREMENT BY 1;

CREATE TABLE AMOUNT (
    ID INT NOT NULL DEFAULT NEXTVAL('SUPERHERO_SEQUENCE') PRIMARY KEY,
    DESCRIPTION VARCHAR(255) NOT NULL,
    AMOUNT FLOAT NOT NULL,
    TYPE NUMERIC(2)
);

COMMIT;